// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizaDjuret.Server.Data;

#nullable disable

namespace QuizaDjuret.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230906070637_fullseed")]
    partial class fullseed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuizaDjuret.Shared.AnswerModel", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnswerId"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnswerId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            AnswerId = 1,
                            IsCorrect = true,
                            QuestionId = 1,
                            Text = "Hund"
                        },
                        new
                        {
                            AnswerId = 2,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "Katt"
                        },
                        new
                        {
                            AnswerId = 3,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "Leopard"
                        },
                        new
                        {
                            AnswerId = 4,
                            IsCorrect = true,
                            QuestionId = 2,
                            Text = "Giraff"
                        },
                        new
                        {
                            AnswerId = 5,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "Zebra"
                        },
                        new
                        {
                            AnswerId = 6,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "Koala"
                        },
                        new
                        {
                            AnswerId = 7,
                            IsCorrect = true,
                            QuestionId = 3,
                            Text = "Känguru"
                        },
                        new
                        {
                            AnswerId = 8,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "Lejon"
                        },
                        new
                        {
                            AnswerId = 9,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "Koala"
                        },
                        new
                        {
                            AnswerId = 10,
                            IsCorrect = true,
                            QuestionId = 4,
                            Text = "Lejon"
                        },
                        new
                        {
                            AnswerId = 11,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "Tiger"
                        },
                        new
                        {
                            AnswerId = 12,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "Panter"
                        },
                        new
                        {
                            AnswerId = 13,
                            IsCorrect = true,
                            QuestionId = 5,
                            Text = "Panda"
                        },
                        new
                        {
                            AnswerId = 14,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "Koala"
                        },
                        new
                        {
                            AnswerId = 15,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "Isbjörn"
                        },
                        new
                        {
                            AnswerId = 16,
                            IsCorrect = true,
                            QuestionId = 6,
                            Text = "Delfin"
                        },
                        new
                        {
                            AnswerId = 17,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "Val"
                        },
                        new
                        {
                            AnswerId = 18,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "Säl"
                        },
                        new
                        {
                            AnswerId = 19,
                            IsCorrect = true,
                            QuestionId = 7,
                            Text = "Örn"
                        },
                        new
                        {
                            AnswerId = 20,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "Falk"
                        },
                        new
                        {
                            AnswerId = 21,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "Kondor"
                        },
                        new
                        {
                            AnswerId = 22,
                            IsCorrect = true,
                            QuestionId = 8,
                            Text = "Flodhäst"
                        },
                        new
                        {
                            AnswerId = 23,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Havssköldpadda"
                        },
                        new
                        {
                            AnswerId = 24,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Val"
                        },
                        new
                        {
                            AnswerId = 25,
                            IsCorrect = true,
                            QuestionId = 9,
                            Text = "Känguru"
                        },
                        new
                        {
                            AnswerId = 26,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "Echidna"
                        },
                        new
                        {
                            AnswerId = 27,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "Koala"
                        },
                        new
                        {
                            AnswerId = 28,
                            IsCorrect = true,
                            QuestionId = 10,
                            Text = "Struts"
                        },
                        new
                        {
                            AnswerId = 29,
                            IsCorrect = false,
                            QuestionId = 10,
                            Text = "Emu"
                        },
                        new
                        {
                            AnswerId = 30,
                            IsCorrect = false,
                            QuestionId = 10,
                            Text = "Pelikan"
                        },
                        new
                        {
                            AnswerId = 31,
                            IsCorrect = true,
                            QuestionId = 11,
                            Text = "Myra"
                        },
                        new
                        {
                            AnswerId = 32,
                            IsCorrect = false,
                            QuestionId = 11,
                            Text = "Fjäril"
                        },
                        new
                        {
                            AnswerId = 33,
                            IsCorrect = false,
                            QuestionId = 11,
                            Text = "Larv"
                        },
                        new
                        {
                            AnswerId = 34,
                            IsCorrect = true,
                            QuestionId = 12,
                            Text = "Säl"
                        },
                        new
                        {
                            AnswerId = 35,
                            IsCorrect = false,
                            QuestionId = 12,
                            Text = "Delfin"
                        },
                        new
                        {
                            AnswerId = 36,
                            IsCorrect = false,
                            QuestionId = 12,
                            Text = "Späckhuggare"
                        },
                        new
                        {
                            AnswerId = 37,
                            IsCorrect = true,
                            QuestionId = 13,
                            Text = "Tran"
                        },
                        new
                        {
                            AnswerId = 38,
                            IsCorrect = false,
                            QuestionId = 13,
                            Text = "Stork"
                        },
                        new
                        {
                            AnswerId = 39,
                            IsCorrect = false,
                            QuestionId = 13,
                            Text = "Flamingo"
                        },
                        new
                        {
                            AnswerId = 40,
                            IsCorrect = true,
                            QuestionId = 14,
                            Text = "Hamster"
                        },
                        new
                        {
                            AnswerId = 41,
                            IsCorrect = false,
                            QuestionId = 14,
                            Text = "Marsvin"
                        },
                        new
                        {
                            AnswerId = 42,
                            IsCorrect = false,
                            QuestionId = 14,
                            Text = "Kanin"
                        },
                        new
                        {
                            AnswerId = 43,
                            IsCorrect = true,
                            QuestionId = 15,
                            Text = "Gepard"
                        },
                        new
                        {
                            AnswerId = 44,
                            IsCorrect = false,
                            QuestionId = 15,
                            Text = "Tiger"
                        },
                        new
                        {
                            AnswerId = 45,
                            IsCorrect = false,
                            QuestionId = 15,
                            Text = "Lejon"
                        },
                        new
                        {
                            AnswerId = 46,
                            IsCorrect = true,
                            QuestionId = 16,
                            Text = "Råtta"
                        },
                        new
                        {
                            AnswerId = 47,
                            IsCorrect = false,
                            QuestionId = 16,
                            Text = "Ekorre"
                        },
                        new
                        {
                            AnswerId = 48,
                            IsCorrect = false,
                            QuestionId = 16,
                            Text = "Igelkott"
                        },
                        new
                        {
                            AnswerId = 49,
                            IsCorrect = true,
                            QuestionId = 17,
                            Text = "Papegoja"
                        },
                        new
                        {
                            AnswerId = 50,
                            IsCorrect = false,
                            QuestionId = 17,
                            Text = "Kolibri"
                        },
                        new
                        {
                            AnswerId = 51,
                            IsCorrect = false,
                            QuestionId = 17,
                            Text = "Pippifågel"
                        },
                        new
                        {
                            AnswerId = 52,
                            IsCorrect = true,
                            QuestionId = 18,
                            Text = "Bi"
                        },
                        new
                        {
                            AnswerId = 53,
                            IsCorrect = false,
                            QuestionId = 18,
                            Text = "Fjäril"
                        },
                        new
                        {
                            AnswerId = 54,
                            IsCorrect = false,
                            QuestionId = 18,
                            Text = "Fluga"
                        },
                        new
                        {
                            AnswerId = 55,
                            IsCorrect = true,
                            QuestionId = 19,
                            Text = "Orangutang"
                        },
                        new
                        {
                            AnswerId = 56,
                            IsCorrect = false,
                            QuestionId = 19,
                            Text = "Gorilla"
                        },
                        new
                        {
                            AnswerId = 57,
                            IsCorrect = false,
                            QuestionId = 19,
                            Text = "Schimpans"
                        },
                        new
                        {
                            AnswerId = 58,
                            IsCorrect = true,
                            QuestionId = 20,
                            Text = "Groda"
                        },
                        new
                        {
                            AnswerId = 59,
                            IsCorrect = false,
                            QuestionId = 20,
                            Text = "Ödla"
                        },
                        new
                        {
                            AnswerId = 60,
                            IsCorrect = false,
                            QuestionId = 20,
                            Text = "Salmander"
                        },
                        new
                        {
                            AnswerId = 61,
                            IsCorrect = true,
                            QuestionId = 21,
                            Text = "Säl"
                        },
                        new
                        {
                            AnswerId = 62,
                            IsCorrect = false,
                            QuestionId = 21,
                            Text = "Späckhuggare"
                        },
                        new
                        {
                            AnswerId = 63,
                            IsCorrect = false,
                            QuestionId = 21,
                            Text = "Haj"
                        },
                        new
                        {
                            AnswerId = 64,
                            IsCorrect = true,
                            QuestionId = 22,
                            Text = "Lejon"
                        },
                        new
                        {
                            AnswerId = 65,
                            IsCorrect = false,
                            QuestionId = 22,
                            Text = "Tiger"
                        },
                        new
                        {
                            AnswerId = 66,
                            IsCorrect = false,
                            QuestionId = 22,
                            Text = "Puma"
                        },
                        new
                        {
                            AnswerId = 67,
                            IsCorrect = true,
                            QuestionId = 23,
                            Text = "Delfin"
                        },
                        new
                        {
                            AnswerId = 68,
                            IsCorrect = false,
                            QuestionId = 23,
                            Text = "Val"
                        },
                        new
                        {
                            AnswerId = 69,
                            IsCorrect = false,
                            QuestionId = 23,
                            Text = "Säl"
                        },
                        new
                        {
                            AnswerId = 70,
                            IsCorrect = true,
                            QuestionId = 24,
                            Text = "Häst"
                        },
                        new
                        {
                            AnswerId = 71,
                            IsCorrect = false,
                            QuestionId = 24,
                            Text = "Ko"
                        },
                        new
                        {
                            AnswerId = 72,
                            IsCorrect = false,
                            QuestionId = 24,
                            Text = "Gris"
                        },
                        new
                        {
                            AnswerId = 73,
                            IsCorrect = true,
                            QuestionId = 25,
                            Text = "Hund"
                        },
                        new
                        {
                            AnswerId = 74,
                            IsCorrect = false,
                            QuestionId = 25,
                            Text = "Katt"
                        },
                        new
                        {
                            AnswerId = 75,
                            IsCorrect = false,
                            QuestionId = 25,
                            Text = "Tiger"
                        },
                        new
                        {
                            AnswerId = 76,
                            IsCorrect = true,
                            QuestionId = 26,
                            Text = "Katt"
                        },
                        new
                        {
                            AnswerId = 77,
                            IsCorrect = false,
                            QuestionId = 26,
                            Text = "Leopard"
                        },
                        new
                        {
                            AnswerId = 78,
                            IsCorrect = false,
                            QuestionId = 26,
                            Text = "Puma"
                        },
                        new
                        {
                            AnswerId = 79,
                            IsCorrect = true,
                            QuestionId = 27,
                            Text = "Örn"
                        },
                        new
                        {
                            AnswerId = 80,
                            IsCorrect = false,
                            QuestionId = 27,
                            Text = "Falk"
                        },
                        new
                        {
                            AnswerId = 81,
                            IsCorrect = false,
                            QuestionId = 27,
                            Text = "Kondor"
                        },
                        new
                        {
                            AnswerId = 82,
                            IsCorrect = true,
                            QuestionId = 28,
                            Text = "Papegoja"
                        },
                        new
                        {
                            AnswerId = 83,
                            IsCorrect = false,
                            QuestionId = 28,
                            Text = "Kolibri"
                        },
                        new
                        {
                            AnswerId = 84,
                            IsCorrect = false,
                            QuestionId = 28,
                            Text = "Pippifågel"
                        },
                        new
                        {
                            AnswerId = 85,
                            IsCorrect = true,
                            QuestionId = 29,
                            Text = "Trana"
                        },
                        new
                        {
                            AnswerId = 86,
                            IsCorrect = false,
                            QuestionId = 29,
                            Text = "Flamingo"
                        },
                        new
                        {
                            AnswerId = 87,
                            IsCorrect = false,
                            QuestionId = 29,
                            Text = "Stork"
                        },
                        new
                        {
                            AnswerId = 88,
                            IsCorrect = true,
                            QuestionId = 30,
                            Text = "Hamster"
                        },
                        new
                        {
                            AnswerId = 89,
                            IsCorrect = false,
                            QuestionId = 30,
                            Text = "Kanin"
                        },
                        new
                        {
                            AnswerId = 90,
                            IsCorrect = false,
                            QuestionId = 30,
                            Text = "Marsvin"
                        },
                        new
                        {
                            AnswerId = 91,
                            IsCorrect = true,
                            QuestionId = 31,
                            Text = "Giraff"
                        },
                        new
                        {
                            AnswerId = 92,
                            IsCorrect = false,
                            QuestionId = 31,
                            Text = "Zebra"
                        },
                        new
                        {
                            AnswerId = 93,
                            IsCorrect = false,
                            QuestionId = 31,
                            Text = "Tiger"
                        },
                        new
                        {
                            AnswerId = 94,
                            IsCorrect = true,
                            QuestionId = 32,
                            Text = "Känguru"
                        },
                        new
                        {
                            AnswerId = 95,
                            IsCorrect = false,
                            QuestionId = 32,
                            Text = "Koala"
                        },
                        new
                        {
                            AnswerId = 96,
                            IsCorrect = false,
                            QuestionId = 32,
                            Text = "Hund"
                        },
                        new
                        {
                            AnswerId = 97,
                            IsCorrect = true,
                            QuestionId = 33,
                            Text = "Panda"
                        },
                        new
                        {
                            AnswerId = 98,
                            IsCorrect = false,
                            QuestionId = 33,
                            Text = "Koala"
                        },
                        new
                        {
                            AnswerId = 99,
                            IsCorrect = false,
                            QuestionId = 33,
                            Text = "Isbjörn"
                        },
                        new
                        {
                            AnswerId = 100,
                            IsCorrect = true,
                            QuestionId = 34,
                            Text = "Flodhäst"
                        },
                        new
                        {
                            AnswerId = 101,
                            IsCorrect = false,
                            QuestionId = 34,
                            Text = "Val"
                        },
                        new
                        {
                            AnswerId = 102,
                            IsCorrect = false,
                            QuestionId = 34,
                            Text = "Havssköldpadda"
                        },
                        new
                        {
                            AnswerId = 103,
                            IsCorrect = true,
                            QuestionId = 35,
                            Text = "Struts"
                        },
                        new
                        {
                            AnswerId = 104,
                            IsCorrect = false,
                            QuestionId = 35,
                            Text = "Emu"
                        },
                        new
                        {
                            AnswerId = 105,
                            IsCorrect = false,
                            QuestionId = 35,
                            Text = "Pelikan"
                        },
                        new
                        {
                            AnswerId = 106,
                            IsCorrect = true,
                            QuestionId = 36,
                            Text = "Myra"
                        },
                        new
                        {
                            AnswerId = 107,
                            IsCorrect = false,
                            QuestionId = 36,
                            Text = "Fjäril"
                        },
                        new
                        {
                            AnswerId = 108,
                            IsCorrect = false,
                            QuestionId = 36,
                            Text = "Bi"
                        },
                        new
                        {
                            AnswerId = 109,
                            IsCorrect = true,
                            QuestionId = 37,
                            Text = "Säl"
                        },
                        new
                        {
                            AnswerId = 110,
                            IsCorrect = false,
                            QuestionId = 37,
                            Text = "Späckhuggare"
                        },
                        new
                        {
                            AnswerId = 111,
                            IsCorrect = false,
                            QuestionId = 37,
                            Text = "Delfin"
                        },
                        new
                        {
                            AnswerId = 112,
                            IsCorrect = true,
                            QuestionId = 38,
                            Text = "Hamster"
                        },
                        new
                        {
                            AnswerId = 113,
                            IsCorrect = false,
                            QuestionId = 38,
                            Text = "Kanin"
                        },
                        new
                        {
                            AnswerId = 114,
                            IsCorrect = false,
                            QuestionId = 38,
                            Text = "Marsvin"
                        },
                        new
                        {
                            AnswerId = 115,
                            IsCorrect = true,
                            QuestionId = 39,
                            Text = "Råtta"
                        },
                        new
                        {
                            AnswerId = 116,
                            IsCorrect = false,
                            QuestionId = 39,
                            Text = "Igelkott"
                        },
                        new
                        {
                            AnswerId = 117,
                            IsCorrect = false,
                            QuestionId = 39,
                            Text = "Ekorre"
                        },
                        new
                        {
                            AnswerId = 118,
                            IsCorrect = true,
                            QuestionId = 40,
                            Text = "Papegoja"
                        },
                        new
                        {
                            AnswerId = 119,
                            IsCorrect = false,
                            QuestionId = 40,
                            Text = "Pippifågel"
                        },
                        new
                        {
                            AnswerId = 120,
                            IsCorrect = false,
                            QuestionId = 40,
                            Text = "Kolibri"
                        });
                });

            modelBuilder.Entity("QuizaDjuret.Shared.QuestionModel", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<int>("CorrectAnswerId")
                        .HasColumnType("int");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<string>("FunFact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            CorrectAnswerId = 1,
                            DifficultyLevel = 1,
                            FunFact = "Hundar är kända för att vara utmärkta simmare och kan simma flera kilometer i öppet vatten",
                            Hint = "Vanligt husdjur och männikans bästavän",
                            ImageURL = "https://i.imgur.com/nMVJSnF.jpeg",
                            Text = "Vad är detta för djur?"
                        },
                        new
                        {
                            QuestionId = 2,
                            CorrectAnswerId = 4,
                            DifficultyLevel = 1,
                            FunFact = "Giraffer sover bara i korta stunder och står upp",
                            Hint = "Har en av de längsta nackarna i djurriket",
                            ImageURL = "https://i.imgur.com/HTwzNY0.jpg",
                            Text = "Vad är detta för djur?"
                        },
                        new
                        {
                            QuestionId = 3,
                            CorrectAnswerId = 7,
                            DifficultyLevel = 1,
                            FunFact = "Känguruer kan hoppa mycket långa sträckor och är extremt snabba",
                            Hint = "Har en karakteristisk pung för att bära sina ungar i",
                            ImageURL = "https://i.imgur.com/LRrt7dB.jpg",
                            Text = "Vad är detta för djur?"
                        },
                        new
                        {
                            QuestionId = 4,
                            CorrectAnswerId = 10,
                            DifficultyLevel = 1,
                            FunFact = "Lejonets rytande kan hörs på flera kilometers avstånd",
                            Hint = "Känd för att vara 'kungen av djungeln'",
                            ImageURL = "https://i.imgur.com/3YTx841.jpg",
                            Text = "Vad är detta för djur?"
                        },
                        new
                        {
                            QuestionId = 5,
                            CorrectAnswerId = 13,
                            DifficultyLevel = 1,
                            FunFact = "Pandor är kända för sin söta och knubbiga utseende",
                            Hint = "Lever i Kina och äter mestadels bambu",
                            ImageURL = "https://i.imgur.com/vVxD2Vr.jpg",
                            Text = "Vad är detta för djur?"
                        },
                        new
                        {
                            QuestionId = 6,
                            CorrectAnswerId = 16,
                            DifficultyLevel = 1,
                            FunFact = "Delfiner kommunicerar med varandra genom att använda olika ljud och klickar",
                            Hint = "Lever i haven och är utmärkta simmare",
                            ImageURL = "https://i.imgur.com/UYNPT5l.jpg",
                            Text = "Vad är detta för djur?"
                        },
                        new
                        {
                            QuestionId = 7,
                            CorrectAnswerId = 19,
                            DifficultyLevel = 1,
                            FunFact = "Örnar har en utmärkt syn och kan se byten från hög höjd",
                            Hint = "Symbol för styrka och frihet",
                            ImageURL = "https://i.imgur.com/KJdADuA.jpg",
                            Text = "Vad är detta för djur?"
                        },
                        new
                        {
                            QuestionId = 8,
                            CorrectAnswerId = 22,
                            DifficultyLevel = 1,
                            FunFact = "Flodhästar är kända för sina massiva käkar och tänder",
                            Hint = "Även om de är kraftiga simmare, så lever de mestadels på land",
                            ImageURL = "https://i.imgur.com/Usfrgma.jpg",
                            Text = "Vad är detta för djur?"
                        },
                        new
                        {
                            QuestionId = 9,
                            CorrectAnswerId = 25,
                            DifficultyLevel = 1,
                            FunFact = "Koalor sover upp till 20 timmar per dyng",
                            Hint = "Lever på en diet som främst består av eukalyptusblad",
                            ImageURL = "https://i.imgur.com/9PzgFus.jpg",
                            Text = "Vad är detta för djur?"
                        },
                        new
                        {
                            QuestionId = 10,
                            CorrectAnswerId = 28,
                            DifficultyLevel = 1,
                            FunFact = "Strutsar är de största och tyngsta fåglarna på jorden",
                            Hint = "Finns i Afrika och är känd för sin långa hals",
                            ImageURL = "https://i.imgur.com/REFAZzh.jpg",
                            Text = "Vad är detta för djur?"
                        },
                        new
                        {
                            QuestionId = 11,
                            CorrectAnswerId = 31,
                            DifficultyLevel = 2,
                            FunFact = "En del myror kan lyfta objekt som är mycket tyngre än de själva",
                            Hint = "Känd för sitt arbete att samla mat",
                            ImageURL = "https://i.imgur.com/qSCH06v.png",
                            Text = "Vad är detta för djur?"
                        },
                        new
                        {
                            QuestionId = 12,
                            CorrectAnswerId = 34,
                            DifficultyLevel = 2,
                            FunFact = "Sälar är skickliga simmare och dykare",
                            Hint = "Lever ofta i närheten av kusten och äter fisk",
                            ImageURL = "https://i.imgur.com/bRlhcaM.jpg",
                            Text = "Vad är detta för djur?"
                        },
                        new
                        {
                            QuestionId = 13,
                            CorrectAnswerId = 37,
                            DifficultyLevel = 2,
                            FunFact = "Tranor är kända för sina graciösa danser under parningssäsongen",
                            Hint = "Lever ofta i våtmarker och har ett karakteristiskt trumpetande ljud",
                            ImageURL = "https://i.imgur.com/pWr4Xxu.jpg",
                            Text = "Vad är detta för djur?"
                        },
                        new
                        {
                            QuestionId = 14,
                            CorrectAnswerId = 40,
                            DifficultyLevel = 2,
                            FunFact = "Hamstrar har kindpåsar där de lagra mat",
                            Hint = "Kan vara hårig eller naken, beroende på ras",
                            ImageURL = "https://i.imgur.com/tWHofmn.png",
                            Text = "Vad är detta för djur?"
                        },
                        new
                        {
                            QuestionId = 15,
                            CorrectAnswerId = 43,
                            DifficultyLevel = 2,
                            FunFact = "Geparder är de snabbaste landdjuren på jorden",
                            Hint = "Lever i Afrika och är en skicklig jägare",
                            ImageURL = "https://i.imgur.com/X7kpZ0P.jpg",
                            Text = "Vad är detta för djur?"
                        },
                        new
                        {
                            QuestionId = 16,
                            CorrectAnswerId = 46,
                            DifficultyLevel = 2,
                            FunFact = "Råttor är mycket intelligenta och kan lösa komplexa problem",
                            Hint = "Kan vara grå, brun eller svart",
                            ImageURL = "https://i.imgur.com/vyesMf1.jpg",
                            Text = "Vad är detta för djur?"
                        },
                        new
                        {
                            QuestionId = 17,
                            CorrectAnswerId = 49,
                            DifficultyLevel = 2,
                            FunFact = "Papegojor kan ha ett mycket brett ordförråd och förstå enkla meningar",
                            Hint = "Kan vara röd, blå, grön eller gul",
                            ImageURL = "https://i.imgur.com/nO4aFC3.jpg",
                            Text = "Vad är detta för djur?"
                        },
                        new
                        {
                            QuestionId = 18,
                            CorrectAnswerId = 52,
                            DifficultyLevel = 2,
                            FunFact = "Bin är viktiga pollinatörer för många växter",
                            Hint = "Gör honung och bor i bikupor",
                            ImageURL = "https://i.imgur.com/tfhdJ40.jpg",
                            Text = "Vad är detta för djur?"
                        },
                        new
                        {
                            QuestionId = 19,
                            CorrectAnswerId = 55,
                            DifficultyLevel = 2,
                            FunFact = "Orangutanger delar omkring 97 % av sin DNA med människor",
                            Hint = "Lever i regnskogen och gillar bananer",
                            ImageURL = "https://i.imgur.com/EPK88mg.jpg",
                            Text = "Vad är detta för djur?"
                        },
                        new
                        {
                            QuestionId = 20,
                            CorrectAnswerId = 58,
                            DifficultyLevel = 2,
                            FunFact = "Groddjur genomgår en förvandling från simmande grodyngel till groda",
                            Hint = "Har en karakteristisk sång under natten",
                            ImageURL = "https://i.imgur.com/TY9PKPZ.jpg",
                            Text = "Vad är detta för djur?"
                        },
                        new
                        {
                            QuestionId = 21,
                            CorrectAnswerId = 61,
                            DifficultyLevel = 3,
                            FunFact = "Sälar är skickliga simmare och dykare",
                            Hint = "Lever ofta i närheten av kusten och äter fisk",
                            ImageURL = "Säl.mp3",
                            Text = "Vilket djur gör detta ljud?"
                        },
                        new
                        {
                            QuestionId = 22,
                            CorrectAnswerId = 64,
                            DifficultyLevel = 3,
                            FunFact = "Lejonets rytande kan höras på flera kilometers avstånd",
                            Hint = "Känd för att vara 'kungen av djungeln'",
                            ImageURL = "Lejon.mp3",
                            Text = "Vilket djur gör detta ljud?"
                        },
                        new
                        {
                            QuestionId = 23,
                            CorrectAnswerId = 67,
                            DifficultyLevel = 3,
                            FunFact = "Delfiner kommunicerar med varandra genom att använda olika ljud och klickar",
                            Hint = "Lever i havet och är en utmärkt simmare",
                            ImageURL = "Delfin.mp3",
                            Text = "Vilket djur gör detta ljud?"
                        },
                        new
                        {
                            QuestionId = 24,
                            CorrectAnswerId = 70,
                            DifficultyLevel = 3,
                            FunFact = "Hästar har en utmärkt förmåga att kommunicera med kroppsspråk",
                            Hint = "Ofta används för ridning och dragarbete",
                            ImageURL = "Häst.mp3",
                            Text = "Vilket djur gör detta ljud?"
                        },
                        new
                        {
                            QuestionId = 25,
                            CorrectAnswerId = 73,
                            DifficultyLevel = 3,
                            FunFact = "Hundar är kända för att vara utmärkta simmare och kan simma flera kilometer i öppet vatten",
                            Hint = "Vanligt husdjur och människans bästavän",
                            ImageURL = "Hund.mp3",
                            Text = "Vilket djur gör detta ljud?"
                        },
                        new
                        {
                            QuestionId = 26,
                            CorrectAnswerId = 76,
                            DifficultyLevel = 3,
                            FunFact = "Katter kan hoppa flera gånger sin egen kroppslängd i en enda hopp",
                            Hint = "Är känd för att jaga möss och andra smådjur",
                            ImageURL = "Katt.mp3",
                            Text = "Vilket djur gör detta ljud?"
                        },
                        new
                        {
                            QuestionId = 27,
                            CorrectAnswerId = 79,
                            DifficultyLevel = 3,
                            FunFact = "Örnar har en utmärkt syn och kan se byten från hög höjd",
                            Hint = "Symbol för styrka och frihet",
                            ImageURL = "Örn.mp3",
                            Text = "Vilket djur gör detta ljud?"
                        },
                        new
                        {
                            QuestionId = 28,
                            CorrectAnswerId = 82,
                            DifficultyLevel = 3,
                            FunFact = "Papegojor kan ha ett mycket brett ordförråd och förstå enkla meningar",
                            Hint = "Kan vara röd, blå, grön eller gul",
                            ImageURL = "Papegoja.mp3",
                            Text = "Vilket djur gör detta ljud?"
                        },
                        new
                        {
                            QuestionId = 29,
                            CorrectAnswerId = 85,
                            DifficultyLevel = 3,
                            FunFact = "Tranor är kända för sina graciösa danser under parningssäsongen",
                            Hint = "Lever ofta i våtmarker och har ett karakteristiskt trumpetande ljud",
                            ImageURL = "Trana.mp3",
                            Text = "Vilket djur gör detta ljud?"
                        },
                        new
                        {
                            QuestionId = 30,
                            CorrectAnswerId = 88,
                            DifficultyLevel = 3,
                            FunFact = "Hamstrar har kindpåsar där de lagra mat",
                            Hint = "Kan vara hårig eller naken, beroende på ras",
                            ImageURL = "Hamster.mp3",
                            Text = "Vilket djur gör detta ljud?"
                        },
                        new
                        {
                            QuestionId = 31,
                            CorrectAnswerId = 91,
                            DifficultyLevel = 4,
                            FunFact = "Giraffer sover bara i korta stunder och står upp",
                            Hint = "Har en av de längsta nackarna i djurriket",
                            ImageURL = "",
                            Text = "Ett långhalsat djur med fläckig päls"
                        },
                        new
                        {
                            QuestionId = 32,
                            CorrectAnswerId = 94,
                            DifficultyLevel = 4,
                            FunFact = "Känguruer kan hoppa mycket långa sträckor och är extremt snabba",
                            Hint = "Har en karakteristisk pung för att bära sina ungar i",
                            ImageURL = "",
                            Text = "Ett pungdjur från Australien som hoppar på sina bakben"
                        },
                        new
                        {
                            QuestionId = 33,
                            CorrectAnswerId = 97,
                            DifficultyLevel = 4,
                            FunFact = "Pandor är kända för sin söta och knubbiga utseende",
                            Hint = "Lever i Kina och äter mestadels bambu",
                            ImageURL = "",
                            Text = "En björnart med svartvita markeringar"
                        },
                        new
                        {
                            QuestionId = 34,
                            CorrectAnswerId = 100,
                            DifficultyLevel = 4,
                            FunFact = "Flodhästar är kända för sina massiva käkar och tänder",
                            Hint = "Även om de är kraftiga simmare, befinner de sig oftast på land",
                            ImageURL = "",
                            Text = "Ett stort, tungt djur som lever i vattnet"
                        },
                        new
                        {
                            QuestionId = 35,
                            CorrectAnswerId = 103,
                            DifficultyLevel = 4,
                            FunFact = "Strutsar är de största och tyngsta fåglarna på jorden",
                            Hint = "Finns i Afrika och är känd för sin långa hals",
                            ImageURL = "",
                            Text = "En stor gräsätande fågel som inte kan flyga"
                        },
                        new
                        {
                            QuestionId = 36,
                            CorrectAnswerId = 106,
                            DifficultyLevel = 4,
                            FunFact = "Myror kan lyfta objekt som är mycket tyngre än de själva",
                            Hint = "Känd för sitt arbete att samla mat",
                            ImageURL = "",
                            Text = "En liten insekt som ofta arbetar i kolonier"
                        },
                        new
                        {
                            QuestionId = 37,
                            CorrectAnswerId = 109,
                            DifficultyLevel = 4,
                            FunFact = "Sälar är skickliga simmare och dykare",
                            Hint = "Lever ofta i närheten av kusten och äter fisk",
                            ImageURL = "",
                            Text = "Ett marint däggdjur med kraftiga morrhår"
                        },
                        new
                        {
                            QuestionId = 38,
                            CorrectAnswerId = 112,
                            DifficultyLevel = 4,
                            FunFact = "Hamstrar har kindpåsar där de lagra mat",
                            Hint = "Kan vara hårig eller naken, beroende på ras",
                            ImageURL = "",
                            Text = "En liten gnagare som ofta ses i burar som husdjur"
                        },
                        new
                        {
                            QuestionId = 39,
                            CorrectAnswerId = 115,
                            DifficultyLevel = 4,
                            FunFact = "Råttor är mycket intelligenta och kan lösa komplexa problem",
                            Hint = "Kan vara grå, brun eller svart",
                            ImageURL = "",
                            Text = "Ett snabbt och smidigt djur som ofta förekommer i städer"
                        },
                        new
                        {
                            QuestionId = 40,
                            CorrectAnswerId = 118,
                            DifficultyLevel = 4,
                            FunFact = "Papegojor kan ha ett mycket brett ordförråd och förstå enkla meningar",
                            Hint = "Kan vara röd, blå, grön eller gul",
                            ImageURL = "",
                            Text = "En färgglad fågel som ofta kan härma mänskliga ljud"
                        });
                });

            modelBuilder.Entity("QuizaDjuret.Shared.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Highscore");
                });

            modelBuilder.Entity("QuizaDjuret.Shared.AnswerModel", b =>
                {
                    b.HasOne("QuizaDjuret.Shared.QuestionModel", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuizaDjuret.Shared.QuestionModel", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
